CREATE DATABASE dbphp7
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE dbphp7;

CREATE TABLE tb_usuarios (
  idusuario int(11) NOT NULL AUTO_INCREMENT,
  deslogin varchar(64) NOT NULL,
  dessenha varchar(256) NOT NULL,
  dtcadastro timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (idusuario)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO tb_usuarios VALUES
(DEFAULT,'teste1','1234560',CURRENT_DATE()),
(DEFAULT,'Rodrigo','1234560',CURRENT_DATE()),
(DEFAULT,'Mariana','1234560',CURRENT_DATE()),
(DEFAULT,'JEnnifer','1234560',CURRENT_DATE());